from django.conf.urls.defaults import *

urlpatterns = patterns('canvas.views',
	(r'^edit/$', 'edit_canvas'),
	(r'^new/$', 'new_canvas'),
	#(r'^save/(?P<elem_id>\d+)/(?P<X>\d{1,4})/(?P<Y>\d{1,4})/$', 'save_element'),
	(r'^save/$', 'save_element'),
	(r'^saveElementWidthHeight/$', 'save_element_width_height'),
	(r'^saveElementCurrentSitting/$','save_element_current_sitting'),
	(r'^savePerson/$', 'save_person_element'),
	(r'^saveDupPerson/$', 'save_dup_person_element'),
	(r'^sit/$', 'drop_person'),
	(r'^sitMulti/$', 'drop_multi_persons'),
	(r'^delfp/$', 'del_float_person'),
	(r'^add/$', 'add_element'),
	(r'^delete/$', 'del_element'),
	(r'^getItem/$', 'get_element_item'),
	(r'^swapPos/$', 'swap_position'),
	(r'^bringToFloatList/$', 'bring_person_to_float_list_by_position'),
	(r'^findTables/$', 'find_tables_strings'),
	(r'^findPersons/$', 'find_persons_strings'),
	(r'^personOnHigherPos/$', 'is_persons_on_higher_position'),
	(r'^floatPersonsFromPos/$', 'bring_person_to_floatlist_from_postion'),
	(r'^updateNumOfGuests/$', 'update_Num_Of_Guests'),
	(r'^getNumOfGuests/$', 'get_Num_Of_Guests'),
	(r'^getMoneyInfo/$', 'get_Money_Info'),
	(r'^writeOperationInfo/$', 'write_Operation'),
	(r'^getOperationsInfo/$', 'get_Operations'),
	(r'^getOperationsInfoNum/$', 'get_OperationsInfoNum'),
	(r'^getGuestsEmails/$', 'get_GuestsEmails'),
	(r'^getElementOrientation/$', 'get_element_orientation'),
	(r'^changeElementOrientation/$', 'change_element_orientation'),
	(r'^changeUserProfile/$', 'change_user_profile'),
	(r'^getOccasionMealAndInvDetails/$', 'get_occasion_meal_and_inv_details'),
	(r'^getPersonItemByFullName/$', 'get_element_item_by_full_name'),
	(r'^fixNumberStatus/$', 'fix_number_status'),
	(r'^getFixNumber/$', 'get_fix_number'),
	(r'^backToNewCanvas/$', 'back_To_New_Canvas'),
	(r'^getMaxY/$', 'get_max_y'),
	(r'^getMaxY/$', 'get_max_x'),
)
